name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Mise à jour chaque nuit
  workflow_dispatch: # Pour tester manuellement
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.isocalendar.halfyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
